<!DOCTYPE html>
<html>
<body>
<div class="page">
    <p>
        Beste<?php if (count($userPasswordResets) == 1): ?> <strong><?= $user->getDisplayName(); ?></strong><?php endif; ?>,<br />
        <br />
        U heeft aangegeven uw wachtwoord te willen wijzigen.<br />
        <?php if (count($userPasswordResets) == 1): ?>
            Klik op de link hieronder om een nieuw wachtwoord in te stellen:
        <?php else: ?>
            Er zijn meerdere gebruikers gevonden met dit E-mailadres. Klik hieronder op de link naast de gebruiker waarvoor u nieuw wachtwoord in wil stellen:
        <?php endif; ?>
    </p>
    <p>
        <table>
            <thead>
                <tr>
                    <th>
                        Gebruiker
                    </th>
                    <th>
                        Link
                    </th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($userPasswordResets as $userPasswordReset):?>
                    <tr>
                        <td>
                            <?= $userPasswordReset['user']->getUserName() ?>
                        </td>
                        <td style="padding-left: 1em;">
                            <a href="<?= $host; ?><?= $this->url('set-password', [],['query'=>['token' => $userPasswordReset['token']->getToken(), 'frontend' => $fromFrontend]]); ?>" target="_blank">
                                wachtwoord wijzigen
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </p>
    <p>
        Met vriendelijke groet,<br />
        <?=$config['mail_app_owner']?>
    </p>
    <br />
    <p>
        [Mocht u geen nieuw wachtwoord hebben aangevraagd, neemt u dan contact op met
        <a mailto="<?=$config['mail_reply_email']?>"><?=$config['mail_reply_name']?></a>]<br />
        [Dit is een automatisch gegenereerde email]
    </p>
</div>
</body>
</html>
