<?php
$form->get('name')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Enter name'
]);

$form->get('description')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Enter description'
]);

$form->get('inherit_roles')->setAttributes([
    'class' => 'form-control',
]);

$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);

$form->prepare();
?>
<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="bg-secondary rounded  p-4">
            <div class="col-sm-12 col-md-12 col-xl-12">
                <div class="row g-4">
                    <h2 class="col-sm-12 col-md-12 col-xl-12 mb-4 text-primary">Add Role</h2>
                </div>
            </div>
            <div class="col-sm-12 col-md-12 col-xl-12">
                <?= $this->form()->openTag($form); ?>

                <div class="form-group mb-2">
                    <?= $this->formLabel($form->get('name')); ?>
                    <?= $this->formElement($form->get('name')); ?>
                    <?= $this->formElementErrors($form->get('name')); ?>
                </div>

                <div class="form-group mb-2">
                    <?= $this->formLabel($form->get('description')); ?>
                    <?= $this->formElement($form->get('description')); ?>
                    <?= $this->formElementErrors($form->get('description')); ?>
                </div>

                <div class="form-group mb-2">
                    <?= $this->formLabel($form->get('inherit_roles')); ?>
                    <?= $this->formElement($form->get('inherit_roles')); ?>
                    <?= $this->formElementErrors($form->get('inherit_roles')); ?>
                </div>

                <?= $this->formElement($form->get('csrf')); ?>

                <div class="row">
                    <div class="col-sm-12 col-md-6 col-xl-6">
                        <?= $this->formElement($form->get('submit')); ?>
                    </div>
                    <div class="col-sm-12 col-md-6 col-xl-6 text-end">
                        <a href="<?= $this->url('beheer/roles', ['action' => 'index']); ?>" class="btn btn-primary"
                           title="Annuleren">Annuleren</a>
                    </div>
                </div>

                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>




