<?php
$form->get('submit')
    ->setAttributes(['class' => 'btn btn-primary'])
    ->setValue('Save');

$form->prepare();
?>

<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="bg-secondary rounded  p-4">
            <div class="col-sm-12 col-md-12 col-xl-12">
                <div class="row g-4">
                    <h2 class="col-sm-12 col-md-12 col-xl-12 mb-4 text-primary">Edit Permissions of <?= $this->escapeHtml($role->getName()) ?></h2>
                </div>
            </div>
            <div class="col-sm-12 col-md-12 col-xl-12">
                <?= $this->form()->openTag($form); ?>
                <table class="table table-striped table-bordered">
                    <tr>
                        <th>Name</th>
                        <th>Description</th>
                    </tr>
                    <?php foreach ($allPermissions as $permission):
                        $element = $form->get('permissions')->get($permission->getName());
                        ?>
                        <tr>
                            <td>
                                <div class="checkbox">
                                    <label><input type="checkbox"
                                                  name="<?= $this->escapeHtmlAttr($element->getName()) ?>"
                                                  value="<?= $this->escapeHtmlAttr($element->getCheckedValue()) ?>"
                                            <?php if ($element->isChecked()) echo 'checked' ?>
                                            <?php if ($element->getAttribute('disabled')) echo 'disabled' ?>>
                                        <?= $this->escapeHtml($element->getLabel()) ?>
                                    </label>
                                    <?= $this->formElementErrors($element); ?>
                                </div>
                            </td>
                            <td>
                                <?= $this->escapeHtml($permission->getDescription()) ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </table>
                <?= $this->formElement($form->get('csrf')); ?>

                <div class="row">
                    <div class="col-sm-12 col-md-6 col-xl-6">
                        <?= $this->formElement($form->get('submit')); ?>
                    </div>
                    <div class="col-sm-12 col-md-6 col-xl-6 text-end">
                        <a href="<?= $this->url('beheer/roles', ['action' => 'edit', 'id' => $role->getId()]); ?>" class="btn btn-primary"
                           title="Annuleren">Annuleren</a>
                    </div>
                </div>

                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>

