<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="bg-secondary rounded  p-4">
                <div class="row g-4">
                    <h2 class="col-sm-12 col-md-12 col-xl-12 mb-4">Manage Roles</h2>
                </div>
                <div class="row g-4">
                    <div class="col-sm-6 col-md-6 col-xl-6">
                        <a class="btn btn-primary" href="<?= $this->url('roles', ['action' => 'add']); ?>">
                            <i class="fas fa-plus-square"></i> New Role
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="bg-secondary rounded  p-4">
                <table class="table table-bordered table-hover table-striped">

                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Date Created</th>
                        <th>Actions</th>
                    </tr>

                    <?php foreach ($roles as $role): ?>

                        <tr>
                            <td><?= $this->escapeHtml($role->getId()); ?></td>
                            <td>
                                <a href="<?= $this->url('roles', ['action' => 'view', 'id' => $role->getId()]); ?>">
                                    <?= $this->escapeHtml($role->getName()); ?>
                                </a>
                            </td>
                            <td><?= $this->escapeHtml($role->getDescription()); ?></a>
                            </td>
                            <td>
                                <nobr><?= (is_object($role->getDateCreated()) ? $this->escapeHtml($role->getDateCreated()->format('Y-m-d')) : ''); ?></nobr>
                            </td>
                            <td>
                                </nobr>
                                <a class="btn btn-info" href="<?= $this->url('roles',
                                    ['action' => 'edit', 'id' => $role->getId()]); ?>">
                                    <span class="glyphicon glyphicon-pencil"></span> Edit
                                </a>
                                <a class="btn btn-danger" href="<?= $this->url('roles',
                                    ['action' => 'delete', 'id' => $role->getId()]); ?>">
                                    <span class="glyphicon glyphicon-remove"></span> Delete
                                </a>
                                </nobr>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </div>
        </div>
    </div>
</div>





