<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="bg-secondary rounded  p-4">
            <div class="col-sm-12 col-md-12 col-xl-12">
                <div class="row g-4">
                    <h2 class="col-sm-12 col-md-12 col-xl-12 mb-4 text-primary">View
                        Role <?= $this->escapeHtml($role->getName()) ?></h2>
                </div>
                <div class="row g-4">
                    <div class="col-sm-6 col-md-6 col-xl-6">
                        <a class="btn btn-primary" href="<?= $this->url('roles',
                            ['action' => 'edit', 'id' => $role->getId()]); ?>">
                            <span class="glyphicon glyphicon-pencil"></span> Edit Role
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-sm-12 col-md-12 col-xl-12">
                <table class="table table-striped table-bordered">
                    <tr>
                        <th>ID:</th>
                        <td><?= $this->escapeHtml($role->getId()) ?></th>
                    </tr>
                    <tr>
                        <th>Name:</th>
                        <td><?= $this->escapeHtml($role->getName()) ?></th>
                    </tr>
                    <tr>
                        <th>Description:</th>
                        <td><?= $this->escapeHtml($role->getDescription()) ?></th>
                    </tr>
                    <tr>
                        <th>Date Created:</th>
                        <td><?= (is_object($role->getDateCreated()) ? $this->escapeHtml($role->getDateCreated()->format('Y-m-d')) : ''); ?></th>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="bg-secondary rounded  p-4">
            <div class="col-sm-12 col-md-12 col-xl-12">
                <div class="row g-4">
                    <h2 class="col-sm-12 col-md-12 col-xl-12 mb-4 text-primary">Permissions</h2>
                </div>
                <div class="row g-4">
                    <div class="col-sm-6 col-md-6 col-xl-6">
                        <a class="btn btn-primary"
                           href="<?= $this->url('roles', ['action' => 'editPermissions', 'id' => $role->getId()]) ?>">
                            <span class="glyphicon glyphicon-check"></span> Edit Permissions
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-sm-12 col-md-12 col-xl-12">
                <table class="table table-striped table-bordered">
                    <tr>
                        <th>Name</th>
                        <th>Description</th>
                    </tr>
                    <?php foreach ($allPermissions as $permission): ?>
                        <tr>
                            <td>
                                <input type="checkbox"
                                       disabled <?php if (isset($effectivePermissions[$permission->getName()])) {
                                    echo 'checked';
                                } ?>>
                                <?= $this->escapeHtml($permission->getName()) ?>
                                <?php if (isset($effectivePermissions[$permission->getName()]) && $effectivePermissions[$permission->getName()] == 'inherited'): ?>
                                    <em>(inherited)</em>
                                <?php endif; ?>
                            </td>
                            <td><?= $this->escapeHtml($permission->getDescription()) ?></td>
                        </tr>
                    <?php endforeach; ?>
                </table>

                <div class="row">
                    <div class="col-sm-12 col-md-12 col-xl-12 text-end">
                        <a href="<?= $this->url('beheer/roles', ['action' => 'index']); ?>" class="btn btn-primary"
                           title="Annuleren">Annuleren</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
