<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="bg-secondary rounded  p-4">
                <div class="row g-4">
                    <h2 class="col-sm-12 col-md-12 col-xl-12 mb-4">Manage Permissions</h2>
                </div>
                <div class="row g-4">
                    <div class="col-sm-6 col-md-6 col-xl-6">
                        <a class="btn btn-primary" href="
    <?= $this->url('permissions', ['action' => 'add']); ?>">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New Permission
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="bg-secondary rounded  p-4">
                <table class="table table-bordered table-hover table-striped">

                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Date Created</th>
                        <th>Actions</th>
                    </tr>

                    <?php foreach ($permissions as $permission): ?>

                        <tr>
                            <td><?= $this->escapeHtml($permission->getId()); ?></td>
                            <td>
                                <a href="<?= $this->url('permissions',
                                    ['action' => 'view', 'id' => $permission->getId()]); ?>">
                                    <?= $this->escapeHtml($permission->getName()); ?>
                                </a>
                            </td>
                            <td><?= $this->escapeHtml($permission->getDescription()); ?></a>
                            </td>
                            <td>
                                <nobr><?= (is_object($permission->getDateCreated()) ? $this->escapeHtml($permission->getDateCreated()->format('Y-m-d')) : ''); ?></nobr>
                            </td>
                            <td>
                                <nobr>
                                    <a class="btn btn-info" href="<?= $this->url('permissions',
                                        ['action' => 'edit', 'id' => $permission->getId()]); ?>">
                                        <span class="glyphicon glyphicon-pencil"></span> Edit
                                    </a>
                                    <a class="btn btn-danger" href="<?= $this->url('permissions',
                                        ['action' => 'delete', 'id' => $permission->getId()]); ?>">
                                        <span class="glyphicon glyphicon-remove"></span> Delete
                                    </a>
                                </nobr>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </div>
        </div>
    </div>
</div>


