<?php
$this->headTitle('View Permission');

$this->mainMenu()->setActiveItemId('permissions');

$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Manage Permissions' => $this->url('permissions'),
    'View Permission' => $this->url('permissions', ['action' => 'view', 'id' => $permission->getId()])
]);
?>

<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="bg-secondary rounded  p-4">
                <div class="row g-4">
                    <h2 class="col-sm-12 col-md-12 col-xl-12 mb-4">View Permission</h2>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="bg-secondary rounded  p-4">
                <table class="table table-bordered table-hover table-striped">
                    <tr>
                        <th>ID:</th>
                        <td><?= $this->escapeHtml($permission->getId()) ?></th>
                    </tr>
                    <tr>
                        <th>Name:</th>
                        <td><?= $this->escapeHtml($permission->getName()) ?></th>
                    </tr>
                    <tr>
                        <th>Description:</th>
                        <td><?= $this->escapeHtml($permission->getDescription()) ?></th>
                    </tr>
                    <tr>
                        <th>Date Created:</th>
                        <td><?= (is_object($permission->getDateCreated()) ? $this->escapeHtml($permission->getDateCreated()->format('Y-m-d')) : ''); ?></th>
                    </tr>
                </table>

                <div class="row">
                    <div class="col-sm-12 col-md-12 col-xl-12 text-end">
                        <a href="<?= $this->url('beheer/permissions', ['action' => 'index']); ?>"
                           class="btn btn-primary"
                           title="Annuleren">Annuleren</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>