<?php

$form->get('email')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'name@example.com'
]);

$form->get('full_name')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'John Doe'
]);

$form->get('status')->setAttributes([
    'class' => 'form-control'
]);

$form->get('password')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Enter password',
]);

$form->get('confirm_password')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Retype password',
]);

$form->get('roles')->setAttributes([
    'class' => 'form-control'
]);

$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);

$form->prepare();
?>

<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="bg-secondary rounded  p-4">
            <div class="col-sm-12 col-md-12 col-xl-12">
                <div class="row g-4">
                    <h2 class="col-sm-12 col-md-12 col-xl-12 mb-4 text-primary">Add User</h2>
                </div>
            </div>
            <div class="col-sm-12 col-md-12 col-xl-12">
                <?= $this->form()->openTag($form); ?>

                <div class="form-group mb-2">
                    <?= $this->formLabel($form->get('email')); ?>
                    <?= $this->formElement($form->get('email')); ?>
                    <?= $this->formElementErrors($form->get('email')); ?>
                </div>

                <div class="form-group mb-2">
                    <?= $this->formLabel($form->get('full_name')); ?>
                    <?= $this->formElement($form->get('full_name')); ?>
                    <?= $this->formElementErrors($form->get('full_name')); ?>
                </div>

                <div class="form-group mb-2">
                    <?= $this->formLabel($form->get('password')); ?>
                    <?= $this->formElement($form->get('password')); ?>
                    <?= $this->formElementErrors($form->get('password')); ?>
                </div>

                <div class="form-group mb-2">
                    <?= $this->formLabel($form->get('confirm_password')); ?>
                    <?= $this->formElement($form->get('confirm_password')); ?>
                    <?= $this->formElementErrors($form->get('confirm_password')); ?>
                </div>

                <div class="form-group mb-2">
                    <?= $this->formLabel($form->get('status')); ?>
                    <?= $this->formElement($form->get('status')); ?>
                    <?= $this->formElementErrors($form->get('status')); ?>
                </div>

                <div class="form-group mb-2">
                    <?= $this->formLabel($form->get('roles')); ?>
                    <?= $this->formElement($form->get('roles')); ?>
                    <?= $this->formElementErrors($form->get('roles')); ?>
                </div>

                <div class="form-group mb-2">
                    <?= $this->formElement($form->get('csrf')); ?>
                    <?= $this->formElementErrors($form->get('csrf')); ?>
                </div>

                <div class="row">
                    <div class="col-sm-12 col-md-6 col-xl-6">
                        <?= $this->formElement($form->get('submit')); ?>
                    </div>
                    <div class="col-sm-12 col-md-6 col-xl-6 text-end">
                        <a href="<?= $this->url('beheer/users', ['action' => 'index']); ?>" class="btn btn-primary"
                           title="Annuleren">Annuleren</a>
                    </div>
                </div>

                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>

