<?php

$form->get('old_password')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Enter old password'
]);

$form->get('new_password')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Enter new password'
]);

$form->get('confirm_new_password')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Re-enter new password'
]);

$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);
$form->prepare();
?>

<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="bg-secondary rounded  p-4">
            <div class="col-sm-12 col-md-12 col-xl-12">
                <div class="row g-4">
                    <h2 class="col-sm-12 col-md-12 col-xl-12 mb-4 text-primary">Change Password for <?= $this->escapeHtml($user->getEmail()) ?></h2>
                </div>
            </div>
            <div class="col-sm-12 col-md-12 col-xl-12">
                <?= $this->form()->openTag($form); ?>

                <div class="form-group mb-2">
                    <?= $this->formLabel($form->get('old_password')); ?>
                    <?= $this->formElement($form->get('old_password')); ?>
                    <?= $this->formElementErrors($form->get('old_password')); ?>
                </div>

                <div class="form-group mb-2">
                    <?= $this->formLabel($form->get('new_password')); ?>
                    <?= $this->formElement($form->get('new_password')); ?>
                    <?= $this->formElementErrors($form->get('new_password')); ?>
                </div>

                <div class="form-group mb-2">
                    <?= $this->formLabel($form->get('confirm_new_password')); ?>
                    <?= $this->formElement($form->get('confirm_new_password')); ?>
                    <?= $this->formElementErrors($form->get('confirm_new_password')); ?>
                </div>

                <?= $this->formElement($form->get('csrf')); ?>

                <div class="row">
                    <div class="col-sm-12 col-md-6 col-xl-6">
                        <?= $this->formElement($form->get('submit')); ?>
                    </div>
                    <div class="col-sm-12 col-md-6 col-xl-6 text-end">
                        <a href="<?= $this->url('beheer/users', ['action' => 'index']); ?>" class="btn btn-primary"
                           title="Annuleren">Annuleren</a>
                    </div>
                </div>

                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>


