<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>


<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="bg-secondary rounded  p-4">
            <div class="col-sm-12 col-md-12 col-xl-12 mb-2">
                <div class="row g-4">
                    <h2 class="col-sm-12 col-md-12 col-xl-12 mb-4 text-primary">View
                        User <?= $this->escapeHtml($user->getEmail()) ?></h2>
                </div>
                <div class="row g-4">
                    <div class="col-sm-6 col-md-6 col-xl-6">
                        <a class="btn btn-primary" href="<?= $this->url('users',
                            ['action' => 'edit', 'id' => $user->getId()]); ?>">
                            <span class="glyphicon glyphicon-pencil"></span> Edit
                        </a>
                        <a class="btn btn-primary" href="<?= $this->url('users',
                            ['action' => 'change-password', 'id' => $user->getId()]); ?>">
                            <span class="glyphicon glyphicon-asterisk"></span> Change Password
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-sm-12 col-md-12 col-xl-12">
                <table class="table table-striped table-bordered">
                    <tr>
                        <th>ID:</th>
                        <td><?= $this->escapeHtml($user->getId()) ?></th>
                    </tr>
                    <tr>
                        <th>E-mail:</th>
                        <td><?= $this->escapeHtml($user->getEmail()) ?></th>
                    </tr>
                    <tr>
                        <th>Full Name:</th>
                        <td><?= $this->escapeHtml($user->getFullName()) ?></th>
                    </tr>
                    <tr>
                        <th>Date Created:</th>
                        <td><?= (is_object($user->getDateCreated()) ? $this->escapeHtml($user->getDateCreated()->format('Y-m-d')) : ''); ?></th>
                    </tr>
                    <tr>
                        <th>Status:</th>
                        <td><?= $this->escapeHtml($user->getStatusAsString()) ?></th>
                    </tr>
                    <tr>
                        <th>Roles:</th>
                        <td><?= $this->escapeHtml($user->getRolesAsString()) ?></th>
                    </tr>
                </table>
                <div class="row">
                    <div class="col-sm-12 col-md-12 col-xl-12 text-end">
                        <a href="<?= $this->url('beheer/users', ['action' => 'index']); ?>" class="btn btn-primary"
                           title="Annuleren">Annuleren</a>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>